name: EcoLobby
version: ${project.version}
main: me.baraban4ik.ecolobby.EcoLobby
api-version: 1.13
author: Baraban4ik
depend: [ProtocolLib]
softdepend: [NBTAPI, PlaceholderAPI]

commands:
  ecolobby:
    usage: /<command> [reload, help, give]
    aliases: [el, elobby, lobby]
  setspawn:
    usage: /<command>
  spawn:
    usage: /<command>

permissions:
  ecolobby.*:
    default: op
    children:
      ecolobby.bypass.*: true

  ecolobby.reload:
    default: op
  ecolobby.help:
    default: true
  ecolobby.give:
    default: op
  ecolobby.setspawn:
    default: op
  ecolobby.spawn:
    default: true

  ecolobby.bypass.*:
    default: op
    children:
      ecolobby.bypass.movements: true

      ecolobby.bypass.chat: true
      ecolobby.bypass.commands: true

      ecolobby.bypass.blocks.break: true
      ecolobby.bypass.blocks.place: true

      ecolobby.bypass.items.move: true
      ecolobby.bypass.items.drop: true
      ecolobby.bypass.items.pickup: true

  ecolobby.bypass.movements:
    default: op

  ecolobby.bypass.chat:
    default: op
  ecolobby.bypass.commands:
    default: op

  ecolobby.bypass.blocks.break:
    default: op
  ecolobby.bypass.blocks.place:
    default: op

  ecolobby.bypass.items.move:
    default: op
  ecolobby.bypass.items.drop:
    default: op
  ecolobby.bypass.items.pickup:
    default: op
