name: EcoLobby
author: Baraban4ik
version: '${project.version}'
api-version: 1.16
main: me.baraban4ik.ecolobby.EcoLobby
softdepend: [PlaceholderAPI, NoteBlockAPI]

commands:
  ecolobby:
    usage: /<command> <reload, help, give, setspawn, spawn>
    aliases: [el, elobby, lobby]
    permission: ecolobby.command
  setspawn:
    usage: /<command> (main / first)
    permission: ecolobby.command.setspawn
  spawn:
    usage: /<command>
    permission: ecolobby.command.spawn

permissions:
  ecolobby.*:
    default: op
    children:
      ecolobby.bypass.*: true

  ecolobby.command.reload:
    default: op
  ecolobby.command.help:
    default: true
  ecolobby.command.give:
    default: op
  ecolobby.command.open:
    default: op
  ecolobby.command.setspawn:
    default: op
  ecolobby.command.spawn:
    default: true

  ecolobby.bypass.*:
    default: op
    children:
      ecolobby.bypass.movements: true

      ecolobby.bypass.chat: true
      ecolobby.bypass.commands: true

      ecolobby.bypass.blocks.break: true
      ecolobby.bypass.blocks.place: true

      ecolobby.bypass.items.move: true
      ecolobby.bypass.items.drop: true
      ecolobby.bypass.items.pickup: true

  ecolobby.bypass.movements:
    default: op

  ecolobby.bypass.chat:
    default: op
  ecolobby.bypass.commands:
    default: op

  ecolobby.bypass.blocks.break:
    default: op
  ecolobby.bypass.blocks.place:
    default: op

  ecolobby.bypass.items.move:
    default: op
  ecolobby.bypass.items.drop:
    default: op
  ecolobby.bypass.items.pickup:
    default: op


