name: EcoLobby
version: '${project.version}'
main: me.baraban4ik.ecolobby.EcoLobby
author: Baraban4ik
softdepend: [PlaceholderAPI]
api-version: 1.19

commands:
  ecolobby:
    usage: /<command>
    aliases: [el, ecol, elobby]
  spawn:
    usage: /<command>
    aliases: [espawn, elspawn]

permissions:
  ecolobby.*:
    default: op
    children:
      ecolobby.bypass.*: true
  ecolobby.spawn:
    default: true
  ecolobby.setspawn:
    default: op
  ecolobby.reload:
    default: op
  ecolobby.give:
    default: op
  ecolobby.bypass.*:
    default: op
    children:
      ecolobby.bypass.move: true
      ecolobby.bypass.chat: true
      ecolobby.bypass.commands: true
      ecolobby.bypass.break: true
      ecolobby.bypass.place: true
      ecolobby.bypass.moveitems: true
      ecolobby.bypass.dropitems: true
  ecolobby.bypass.move:
    default: op
  ecolobby.bypass.chat:
    default: op
  ecolobby.bypass.commands:
    default: op
  ecolobby.bypass.break:
    default: op
  ecolobby.bypass.place:
    default: op
  ecolobby.bypass.moveitems:
    default: op
  ecolobby.bypass.dropitems:
    default: op
